import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Basir",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
    {
      name: "Pallukuru mohan kumar",
      email: "mohan@gmail.com",
      password: bcrypt.hashSync("123123123"),
      isAdmin: true,
    },
  ],
  products: [
   
    {
      name: "Azithromycin 500",
      slug: " tablets",
      category: "azicip",
      image: "/images/azithromycin.png",
      images: [],
      description: "anti-biotics",
      brand: "cipal",
      price: 60,
      countInStock: 10,
      rating: 3.5,
      numReviews: 10,
      reviews: [],
    },
  
  {
      name: "p-250",
      slug: "tablets",
      category: "dolo250",
      image: "/images/Dolo.png",
      images: [],
      description: "fever",
      brand: "micro labs limitied",
      price: 38,
      countInStock: 10,
      rating: 3.5,
      numReviews: 10,
      reviews: [],
    },
  
  
  
  
  
  {
      name: "lactogen-3",
      slug: " milk powder",
      category: "azicip",
      image: "/images/lactogen3.png",
      images: [],
      description: "Nestle",
      brand: "cipal",
      price: 460,
      countInStock: 8,
      rating: 2.5,
      numReviews: 10,
      reviews: [],
    },
  
  {
      name: "Dexa",
      slug: "inj",
      category: " diclofenac ",
      image: "/images/Dexa.png",
      images: [],
      description: "Painkiller",
      brand: "Zydus geo",
      price: 60,
      countInStock: 10,
      rating: 3.5,
      numReviews: 10,
      reviews: [],
    },
  
  
  
  {
      name: "Surgical masks",
      slug: " surgical",
      category: "masks",
      image: "/images/mask.png",
      images: [],
      description: "cold/fever",
      brand: "General",
      price: 250,
      countInStock: 100,
      rating: 3.5,
      numReviews: 10,
      reviews: [],
    },
  
  {
      name: "Human Mixtard 30/70",
      slug: "Insullion",
      category: "mixtard",
      image: "/images/humanmixtard.png",
      description: "Diabtetic/insulin isophane/nph(70%)+human insulin/soluble insulin(30%)",
      images: [],
      brand: "Novo pvt ltd",
      price: 153.64,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      reviews: [],
    },
  
  {
      name: "orls",
      slug: "energy drinks",
      category: "apple",
      image: "/images/orls.png",
      images: [],
      description: "Drinks",
      brand: "Jhonson",
      price: 45,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      reviews: [],
    },
  
  
  
  
  {
      name: "Multiplex",
      slug: " Vitamin",
      category: "beplex",
      image: "/images/multiprex.png",
      images: [],
      description: "anti-biotics",
      brand: "Multivitamin, multiminerals & Antioxidant Soft Gelatin Capsules ",
      price: 379,
      countInStock: 8,
      rating: 4.5,
      numReviews: 10,
      reviews: [],
   },
  
  {
      name: "Protinex",
      slug: "Powder",
      category: "ensure",
      image: "/images/Protinex.png",
      images: [],
      description: "Adults Protein Powder",
      brand: "Dandone",
      price: 750,
      countInStock: 8,
      rating: 4.5,
      numReviews: 10,
      reviews: [],
    },
  
  
  
  {
      name: "Nua ultra",
      slug: "Sanitary pads",
      category: "Stayfree",
      image: "/images/nua.png",
      images: [],
      description: "pads",
      brand: "General",
      price: 45,
      countInStock: 6,
      rating: 2.4,
      numReviews: 10,
      reviews: [],
    },
    {
  name: "Augmentin 625",
  slug: "augmentin-625-tablet",
  category: "antibiotic",
  image: "/images/augmentin.png",
  images: [],
  description: "Antibiotic tablet for bacterial infections",
  brand: "GSK",
  price: 190,
  countInStock: 12,
  rating: 4.3,
  numReviews: 15,
  reviews: [],
},
{
  name: "Cetirizine",
  slug: "cetirizine-tablet",
  category: "allergy",
  image: "/images/cetirizine.png",
  images: [],
  description: "Anti-allergic medicine",
  brand: "Cipla",
  price: 25,
  countInStock: 50,
  rating: 4.0,
  numReviews: 8,
  reviews: [],
},
{
  name: "Pantoprazole 40",
  slug: "pantoprazole-40-tablet",
  category: "gastric",
  image: "/images/pantoprazole.png",
  images: [],
  description: "Acidity and GERD relief",
  brand: "Sun Pharma",
  price: 70,
  countInStock: 14,
  rating: 3.8,
  numReviews: 9,
  reviews: [],
},
{
  name: "Dolo 650",
  slug: "dolo-650-tablet",
  category: "fever-pain",
  image: "/images/dolo650.png",
  images: [],
  description: "Pain and fever reducer",
  brand: "Micro Labs",
  price: 30,
  countInStock: 25,
  rating: 4.6,
  numReviews: 25,
  reviews: [],
},
{
  name: "Metformin 500",
  slug: "metformin-500-tablet",
  category: "diabetes",
  image: "/images/metformin.png",
  images: [],
  description: "Anti-diabetic tablet",
  brand: "USV",
  price: 40,
  countInStock: 20,
  rating: 4.2,
  numReviews: 11,
  reviews: [],
},
{
  name: "Atorvastatin 10",
  slug: "atorvastatin-10-tablet",
  category: "cholesterol",
  image: "/images/atorvastatin.png",
  images: [],
  description: "Reduces bad cholesterol",
  brand: "Pfizer",
  price: 95,
  countInStock: 10,
  rating: 4.1,
  numReviews: 6,
  reviews: [],
},
{
  name: "Montair LC",
  slug: "montair-lc-tablet",
  category: "allergy",
  image: "/images/montairlc.png",
  images: [],
  description: "Anti-allergic combo tablet",
  brand: "Cipla",
  price: 165,
  countInStock: 10,
  rating: 4.0,
  numReviews: 7,
  reviews: [],
},
{
  name: "Domperidone",
  slug: "domperidone-tablet",
  category: "vomiting",
  image: "/images/domperidone.png",
  images: [],
  description: "Prevents nausea and vomiting",
  brand: "Torrent",
  price: 55,
  countInStock: 15,
  rating: 3.7,
  numReviews: 5,
  reviews: [],
},
{
  name: "Amoxicillin 500",
  slug: "amoxicillin-500-tablet",
  category: "antibiotic",
  image: "/images/amoxicillin.png",
  images: [],
  description: "Broad spectrum antibiotic",
  brand: "Cipla",
  price: 90,
  countInStock: 9,
  rating: 4.4,
  numReviews: 12,
  reviews: [],
},
{
  name: "Telmisartan 40",
  slug: "telmisartan-40-tablet",
  category: "bp-medicine",
  image: "/images/telmisartan.png",
  images: [],
  description: "Blood pressure control tablet",
  brand: "Glenmark",
  price: 120,
  countInStock: 10,
  rating: 4.3,
  numReviews: 10,
  reviews: [],
},

  ],
};
export default data;